# Generated by Django 4.2.6 on 2023-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateTimeField(verbose_name='Дата отправления'),
        ),
    ]
